version: '3'

services:
  file-sync:
    build: 
      context: file-sync/ 
    container_name: file-sync 
    image: swarm-manager:5000/brcms/file-sync
    volumes:
     - /mnt/app_data/:/mnt/app_data
     - /var:/mnt/host/var
    environment:
      NODENAME: '${HOSTNAME}'
    deploy:
      mode: global
      restart_policy: 
        condition: any
      labels:
        com.busy-rooms.description: "Mirroring /var/app_data"
    networks:
      - default

  file-sync-daemon-1:
    build:
      context: file-sync-daemon/
    container_name: file-sync-daemon-1    
    ports:
            - "9991:9999"
    environment:
      NODENAME: '${HOSTNAME}'
      ADVERTISE_PORT: 9991
    image: swarm-manager:5000/brcms/file-sync-daemon
    volumes:
     - /mnt/app_data/:/mnt/app_data
     - /var:/mnt/host/var
    deploy:
      mode: global
      restart_policy: 
        condition: any
      labels:
        com.busy-rooms.description: "Listening on 9991"
    networks:
      - default
    depends_on: 
     - "file-sync"
    command: ["./wait-for-file-sync.sh","./main.sh"]
  file-sync-daemon-2:
    build:
      context: file-sync-daemon/
    container_name: file-sync-daemon-2    
    ports:
      - "9992:9999"
    environment:
      ADVERTISE_PORT: 9992
      NODENAME: '${HOSTNAME}'
    image: swarm-manager:5000/brcms/file-sync-daemon
    volumes:
      - /mnt/app_data/:/mnt/app_data
      - /var:/mnt/host/var
    deploy:
      mode: global
      restart_policy: 
        condition: any
      labels:
        com.busy-rooms.description: "Listening on 9992"
    networks:
      - default
    depends_on: 
     - "file-sync"
    command: ["./wait-for-file-sync.sh","./main.sh"]
  file-sync-daemon-3:
    build:
      context: file-sync-daemon/
    container_name: file-sync-daemon-3    
    ports:
            - "9993:9999"
    environment:
      ADVERTISE_PORT: 9993
      NODENAME: '${HOSTNAME}'
    image: swarm-manager:5000/brcms/file-sync-daemon
    volumes:
     - /mnt/app_data/:/mnt/app_data
     - /var:/mnt/host/var
    deploy:
      mode: global
      restart_policy: 
        condition: any
      labels:
        com.busy-rooms.description: "Listening on 9993"
    networks:
      - default
    depends_on: 
     - "file-sync"
    command: ["./wait-for-file-sync.sh","./main.sh"]

  inter-sync-1:
    extra_hosts:
      - "node-1: 10.156.0.2"
      - "node-2: 10.156.0.3"
      - "node-3: 10.156.0.4"
      - "node-4: 10.156.0.5"
    build:
      context: inter-sync/
    container_name: inter-sync-1
    image: swarm-manager:5000/brcms/inter-sync
    volumes:
     - /mnt/app_data/:/mnt/app_data
     - /var:/mnt/host/var
    environment:
      NODENAME: '${HOSTNAME}'
    deploy:
      mode: global
      restart_policy: 
        condition: on-failure
      labels:
        com.busy-rooms.description: "Seeking sibling"
    networks:
      - default
    depends_on: 
     - "file-sync"
    command: ["./wait-for-file-sync.sh","./main.sh"]
  inter-sync-2:
    extra_hosts:
      - "node-1: 10.156.0.2"
      - "node-2: 10.156.0.3"
      - "node-3: 10.156.0.4"
      - "node-4: 10.156.0.5"
    build:
      context: inter-sync/
    container_name: inter-sync-2    
    image: swarm-manager:5000/brcms/inter-sync
    volumes:
     - /mnt/app_data/:/mnt/app_data
     - /var:/mnt/host/var
    environment:
      NODENAME: '${HOSTNAME}'
    deploy:
      mode: global
      restart_policy: 
        condition: on-failure
      labels:
        com.busy-rooms.description: "Seeking sibling"
    networks:
      - default
    depends_on: 
     - "file-sync"
    command: ["./wait-for-file-sync.sh","./main.sh"]
  inter-sync-3:
    extra_hosts:
      - "node-1: 10.156.0.2"
      - "node-2: 10.156.0.3"
      - "node-3: 10.156.0.4"
      - "node-4: 10.156.0.5"
    build:
      context: inter-sync/
    container_name: inter-sync-3    
    image: swarm-manager:5000/brcms/inter-sync
    volumes:
     - /mnt/app_data/:/mnt/app_data
     - /var:/mnt/host/var
    environment:
      NODENAME: '${HOSTNAME}'
    deploy:
      mode: global
      restart_policy: 
        condition: on-failure
      labels:
        com.busy-rooms.description: "Seeking sibling"
    networks:
      - default
    depends_on: 
     - "file-sync"
    command: ["./wait-for-file-sync.sh","./main.sh"]


networks:
  default:
    external:
      name: swarm-net

