version: '3'

services:
  file-sync:
    build: 
      context: file-sync/ 
    container_name: file-sync 
    image: swarm-manager:5000/brcms/file-sync 
    volumes:
     - /mnt/app_data/:/mnt/app_data
     - /var:/mnt/host/var
    environment:
      NODENAME: '${HOSTNAME}'
    deploy:
      mode: global
      restart_policy: 
        condition: any
      labels:
        com.busy-rooms.description: "Mirroring /var/app_data"
    networks:
      - default

networks:
  default:
    external:
      name: swarm-net

